### ISSUE TITLE
Comparison with OctoPrint-TPLinkSmartplug

### ISSUE THREAD

**Issue by renatobo** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#5]
Thanks for effort!
What's the difference between this plugin and https://github.com/jneilliii/OctoPrint-TPLinkSmartplug ?
It seems like OctoPrint-TPLinkSmartplug already has all the features planned here.

**Comment by jamesmccannon02** [comment]
When connecting to the SmartPlug, it uses the Kasa library rather than the reversed engineered method used in the other plugin. This will allow this to become a more feature rich plugin as I develop it but also easier to maintain and keep bug free moving into the future as the kasa library is always being updated to support the newer smart plugs.

I have been in contact with the maintainer of the other plugin and he has commented that this is a more efficient plugin to use. To help me though, it would be great if you use mine and then give feedback and features you want to see as you have experience with both

**Comment by jamesmccannon02** [comment]
There is an open discussion on the discussion page. Please continue there

**Comment by jangrewe** [comment]
As i'm currently using the `tplinksmartplug` plugin and love all the features, i'll stick to that one even if it uses an RE method. 
But: wouldn't it make more sense to just fork and refactor it, so that it uses the Kasa library, instead of reinventing the wheel, just with a different rubber compound?
